web:
  upload-path: /data/upload/
spring:
  freemarker:
    template-loader-path: classpath:/templates
  resources:
    static-locations: classpath:/static/,classpath:/ueditor/,file:${web.upload-path}
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #    org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  mail:
    host: smtp.163.com
    username: 13218016163@163.com
    password: luwei13218016163
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    port: 465

server:
  port: 80
